#ifndef POINT_LIGHT_FLAGS_HLSLI
#define POINT_LIGHT_FLAGS_HLSLI

#define POINT_LIGHT_FLAG_PORTAL_STRICT (1u << 0)
#define POINT_LIGHT_FLAG_SHADOW (1u << 1)
#define POINT_LIGHT_FLAG_SIMPLE (1u << 2)

#define POINT_LIGHT_FLAG_INITIALISED (1u << 8)
#define POINT_LIGHT_FLAG_DISABLED (1u << 9)
#define POINT_LIGHT_FLAG_INVERSE_SQUARE (1u << 10)
#define POINT_LIGHT_FLAG_LINEAR (1u << 11)
#define POINT_LIGHT_FLAG_PARTICLE (1u << 12)
#define POINT_LIGHT_FLAG_SPOT (1u << 13)
#define POINT_LIGHT_FLAG_OMNIDIRECTIONAL (1u << 14)

#endif
